### ISSUE TITLE
目标领航－目的地列表的几个问题

### ISSUE THREAD

**Issue by masuo86** [TopSoup/navigate#12]
1.目的地列表－选项：重复打开，会记录上次的选择；应每次点击选项，都是选择第一个
2.目的地列表：其他功能窗口返回目的地列表窗口时，菜单无法选择在上一次项上，而是总是第一个
3.短信发送，对方手机收不到短信

**Comment by virqin** [comment]
短信发送联系人应该为char不是AECHAR
已修改, 目的地列表发送的短信格式不对,需要修改

**Comment by masuo86** [comment]
全部问题已经修改，并已经验证
