### ISSUE TITLE
版本信息窗口的几个问题

### ISSUE THREAD

**Issue by masuo86** [TopSoup/navigate#13]
1.窗口：应去掉选择按钮
2.窗口：点击返回，会退出程序；应该返回主窗口

**Comment by virqin** [comment]
已修改,请验证

**Comment by masuo86** [comment]
问题２没有解决
１．版本界面需要点击两次，才能返回主界面
２．返回主界面时，菜单选择没有在“版本说明”上

**Comment by virqin** [comment]
1 显示版本页面会有屏蔽按键, 点击两次是打开版本页面后第一次的返回键消息没有送入到我们程序中
2 已修改
