### ISSUE TITLE
添加桌面启动方式

### ISSUE THREAD

**Issue by virqin** [TopSoup/navigate#19]
现在程序每次都到下载中才能调用，需要与海信沟通做成能够在九宫格调用方式

**Comment by masuo86** [comment]
做成rom,应该就是到九宫格的，我发邮件问问

**Comment by masuo86** [comment]
已经发送邮件，等待回复

**Comment by masuo86** [comment]
此任务海信可以做，但是需要提需求，而提需求需走商务流程。
已经和产品经理沟通，后续事宜由市场推动，看市场是否需要
